### ISSUE TITLE
[*] <Ctrl + C> detected. Exiting safely...

### ISSUE THREAD

**Issue by roysimk** [new92/InstaTools#30]
im trying to run any script
but get this output : "[*] <Ctrl + C> detected. Exiting safely..." 
im not clicking cntl + C its just saying it for some reason

**Comment by new92** [comment]
Hi,
Please be more specific which scripts did you run ?
The specific error message is printed if one of the following error occurs: KeyboardInterrupt, EOFError
We can eliminate the KeyboardInterrupt error since you're saying that you don't hit Ctrl + C so it remains the EOFError which occurs if you provide an empty input or press the keys: <Ctrl> + <D> or <Ctrl> + <Z>.
Also it would be helpful if you included a screenshot of the error or the full error message.
